#!/usr/bin/env python3
import colors as c
import random
import time

print(c.clear)

snake = '''
  _________ _______      _____   ____  __.___________
   /   _____/ \      \    /  _  \ |    |/ _|\_   _____/
    \_____  \  /   |   \  /  /_\  \|      <   |    __)_ 
     /        \/    |    \/    |    \    |  \  |        \\
     /_______  /\____|__  /\____|__  /____|__ \/_______  /
             \/         \/         \/        \/        \/ 
'''
while True:
    for verse in range(5):

        for badger in range(12):
            print(c.blue + 'Badgers!')
            time.sleep(0.38)

        for mushroom in range(2):
            print(c.red + 'Mushrooms!')
            time.sleep(0.8)
        
        time.sleep(0.38)    
        print(c.clear)

    print(c.clear)
    print(snake)
    time.sleep(6)
    print(c.clear)
