#!/usr/bin/env python3
import colors as c
import time
import random
from utils import ask

print(c.blue + "Welcome to madlibs!")

text = c.magenta + '''
I walked into {place} and I saw this mysterious {noun}. 
I started to walk closer to the {noun}
and a {animal} came and attacked me. 
It was a weird {color} color. Then it started to
freak out and out of it's butt came a/an {object}. 
I trew it on the ground and more and
more of the {object} kept coming out of it.
It started to shake violently.
I tried to run away but it was to big of an
exlposion and I was consumed in the wave of destruction.
'''

words = {
    "place" : None,
    "noun" : None,
    "animal" : None,
    "color" : None,
    "object" : None
}

print(c.clear + c.blue + '''
Welcome to Madlibs. Enter your answers.
''' + c.reset)

answers = {}
for key in words:
    prompt = key
    answer = ask("Enter " + prompt + ": ")
    answers[key] = answer

print(text.format(**answers))
