#!/usr/bin/env python3
import colors as c
import time

print(c.clear)
hundreths = 1
while True:
    time.sleep(0.01)
    print(c.clear)
    print(c.cyan + '[Control C to stop]' + c.reset, end=': ')
    print(hundreths)
    hundreths += 1
