#!/usr/bin/env python3
import colors as c
import random

sides = []

sides.append("1")
sides.append("2")
sides.append("3")
sides.append("4")
sides.append("5")
sides.append("6")

while True:
  side = random.choice(sides)
  print("rolled: " + side, end= ' ')
  input()

