#!/usr/bin/env python3
import random
import colors as c

print(c.clear)
print('Welcome to eightball!')

answers = [
'yes',
'no',
'maybe'
]

while True:
    question = input('> ')
    if 'goodbye' in question:
        exit()
    answer = random.choice(answers)
    print(answer)
