#!/usr/bin/env python3
import colors as c
import time
import random

print(c.clear + c.orange + '''
I hate math, why do I do this.
''' + c.reset)

number = input(c.magenta + 'Why would ask me these things, your not smart enough? Okay then....put in your number: ')
print(c.cyan + 'Alright, here are the ' + number + c.cyan + ' multiplication table.' + c.reset)

for count in range(12,0,-1):
    print(str(count) + ' x ' + number, end=' = ')
    print(int(number) * count)
