#!/usr/bin/env python3
import colors as c
waffles = input(c.yellow + 'Do you like waffles?')
    if waffles is 'yes':
        print('We all like waffles!')
            else:
                print(c.base3 + 'You have a heart of black stone. :[')

pancakes = input(c.orange + 'Do you like pancakes?')
    if pancakes is 'yes':
        print('We all like pancakes!')
            else:
                print('You belong in a mental institution. :{')
french = input(c.red + 'Do you like french toast?')
    if french is 'yes':
        print('We all like french toast!')
            else:
                print('Oh....okay')
